# Generated by Django 6.0 on 2025-12-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='payment_details',
        ),
    ]
