# Generated by Django 6.0 on 2025-12-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_remove_tree_payment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='sponsors/')),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tree',
            name='image',
            field=models.ImageField(default='images/logo.png', upload_to='trees/'),
        ),
    ]
