# Generated by Django 6.0 on 2025-12-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_sponsor_alter_tree_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
