# Generated by Django 6.0 on 2025-12-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_delete_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
