# Generated by Django 6.0 on 2025-12-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='second_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
