# Generated by Django 6.0 on 2025-12-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_tree_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
