# Generated by Django 6.0 on 2025-12-10 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_payment_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='event',
        ),
    ]
