# Generated by Django 6.0 on 2025-12-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='images/img.png', upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='NAIROBI', max_length=100),
        ),
    ]
